### ISSUE TITLE
subprocess.CalledProcessError: Command '['ns-render', '--tyro-print-completion', 'bash']' returned non-zero exit status 1. While running nerfStudio from docker image

### ISSUE THREAD

**Issue by Napolean29** [nerfstudio-project/nerfstudio#1056] opened 2022-11-30 06:43 UTC
[09:49:20] 🤷 .zshrc not found, skipping.                                                                 install.py:202
           🔍 Found .bashrc!                                                                              install.py:204
[09:49:21] ✔ Wrote new completion to /data/dl/nerfstudio/scripts/completions/bash/_ns-dev-test!           install.py:109
           ✔ Wrote new completion to /data/dl/nerfstudio/scripts/completions/bash/_ns-install-cli!        install.py:109
           ✔ Wrote new completion to /data/dl/nerfstudio/scripts/completions/bash/_ns-process-data!       install.py:109
[09:49:25] ✔ Wrote new completion to /data/dl/nerfstudio/scripts/completions/bash/_ns-eval!               install.py:109
           ✔ Wrote new completion to /data/dl/nerfstudio/scripts/completions/bash/_ns-download-data!      install.py:109
[09:49:29] ✔ Wrote new completion to /data/dl/nerfstudio/scripts/completions/bash/_ns-train!              install.py:109
Traceback (most recent call last):
  File "/usr/local/bin/ns-install-cli", line 8, in <module>
    sys.exit(entrypoint())
  File "/data/dl/nerfstudio/scripts/completions/install.py", line 274, in entrypoint
    tyro.cli(main, description=__doc__)
  File "/usr/local/lib/python3.8/dist-packages/tyro/_cli.py", line 125, in cli
    _cli_impl(
  File "/usr/local/lib/python3.8/dist-packages/tyro/_cli.py", line 326, in _cli_impl
    out, consumed_keywords = _calling.call_from_args(
  File "/usr/local/lib/python3.8/dist-packages/tyro/_calling.py", line 194, in call_from_args
    return unwrapped_f(*args, **kwargs), consumed_keywords  # type: ignore
  File "/data/dl/nerfstudio/scripts/completions/install.py", line 243, in main
    completion_paths = list(
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 619, in result_iterator
    yield fs.pop().result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/data/dl/nerfstudio/scripts/completions/install.py", line 245, in <lambda>
    lambda path_or_entrypoint_and_shell: _generate_completion(
  File "/data/dl/nerfstudio/scripts/completions/install.py", line 98, in _generate_completion
    new = subprocess.run(
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ns-render', '--tyro-print-completion', 'bash']' returned non-zero exit status 1.

!!!!While running nerfStudio from docker image 0.1.11!!!!!

**Comment by ps1x** [comment] 2022-12-01 21:54
Having exaclty same issue.

**Comment by rishikeshrmadan** [comment] 2022-12-01 23:29
@ps1x @Napolean29 @brentyi are you running an old NVidia driver version and/or in headless mode? I tried in two different machines, and got this error in the machine with the older driver that's running headless, I cannot update the drivers there myself to check if they are the cause. The other machine works just fine.

**Comment by ps1x** [comment] 2022-12-02 09:14
I'm using fedora 37. Driver is in "hybrid" mode. Driver version: 520.56.06

**Comment by brentyi** [comment] 2022-12-02 19:40
I haven't been able to reproduce this error myself, but @ps1x @Napolean29 can either of you try building the docker image from the latest version of the Github code?

eg this command from the [guide](https://github.com/nerfstudio-project/nerfstudio/blob/main/docs/quickstart/installation.md#use-docker-image):
```
docker build --tag nerfstudio -f Dockerfile .
```

I'd expect it to still fail, but with #1068 merged the error message should at least be more useful.

**Comment by Napolean29** [comment] 2022-12-04 13:49
<img width="562" alt="Screenshot 2022-12-04 at 7 18 46 PM" src="https://user-images.githubusercontent.com/54025067/205494294-743230b6-6088-4444-8736-6e2f467ed76e.png">
configuration I am using

**Comment by ps1x** [comment] 2022-12-05 13:03
> I haven't been able to reproduce this error myself, but @ps1x @Napolean29 can either of you try with the latest docker image (0.1.12)?
> 
> I'd expect it to still fail, but with #1068 merged the error message should at least be more useful.

```
[14:03:31] ✔ Wrote new completion to /home/user/nerfstudio/scripts/completions/bash/_ns-eval!             install.py:117
           ❌ Completion script generation failed: ['ns-train', '--tyro-print-completion', 'bash']        install.py:107
           ✔ Wrote new completion to /home/user/nerfstudio/scripts/completions/bash/_ns-download-data!    install.py:117
           Traceback (most recent call last):                                                             install.py:111
             File "/home/user/.local/bin/ns-train", line 5, in <module>                                                 
               from scripts.train import entrypoint                                                                     
             File "/home/user/nerfstudio/scripts/train.py", line 50, in <module>                                        
               from nerfstudio.configs.method_configs import AnnotatedBaseConfigUnion                                   
             File "/home/user/nerfstudio/nerfstudio/configs/method_configs.py", line 45, in <module>                    
               from nerfstudio.field_components.temporal_distortions import TemporalDistortionKind                      
             File "/home/user/nerfstudio/nerfstudio/field_components/__init__.py", line 17, in <module>                 
               from .encodings import Encoding, ScalingAndOffset                                                        
             File "/home/user/nerfstudio/nerfstudio/field_components/encodings.py", line 34, in <module>                
               import tinycudann as tcnn                                                                                
             File "/home/user/.local/lib/python3.8/site-packages/tinycudann/__init__.py", line 9, in                    
           <module>                                                                                                     
               from tinycudann.modules import free_temporary_memory, NetworkWithInputEncoding, Network,                 
           Encoding                                                                                                     
             File "/home/user/.local/lib/python3.8/site-packages/tinycudann/modules.py", line 33, in                    
           <module>                                                                                                     
               if _C is None:                                                                                           
           NameError: name '_C' is not defined                                                                          
                                                                                                                        
Traceback (most recent call last):
           ✔ Wrote new completion to /home/user/nerfstudio/scripts/completions/bash/_ns-render!           install.py:117
(●     ) ✍  Generating completions...  File "/home/user/.local/bin/ns-install-cli", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/user/nerfstudio/scripts/completions/install.py", line 282, in entrypoint
    tyro.cli(main, description=__doc__)
  File "/home/user/.local/lib/python3.8/site-packages/tyro/_cli.py", line 125, in cli
    _cli_impl(
  File "/home/user/.local/lib/python3.8/site-packages/tyro/_cli.py", line 326, in _cli_impl
    out, consumed_keywords = _calling.call_from_args(
  File "/home/user/.local/lib/python3.8/site-packages/tyro/_calling.py", line 194, in call_from_args
    return unwrapped_f(*args, **kwargs), consumed_keywords  # type: ignore
  File "/home/user/nerfstudio/scripts/completions/install.py", line 251, in main
    completion_paths = list(
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 619, in result_iterator
    yield fs.pop().result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/user/nerfstudio/scripts/completions/install.py", line 253, in <lambda>
    lambda path_or_entrypoint_and_shell: _generate_completion(
  File "/home/user/nerfstudio/scripts/completions/install.py", line 112, in _generate_completion
    raise e
  File "/home/user/nerfstudio/scripts/completions/install.py", line 99, in _generate_completion
    new = subprocess.run(
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ns-train', '--tyro-print-completion', 'bash']' returned non-zero exit status 1.
```

**Comment by Sandros94** [comment] 2022-12-05 17:45
So I'm getting the same issue that @ps1x is getting (ns-train's error) on 0.1.12

I'm using the latest docker desktop via WSL2, on win11 and a 1660 ti

if I run `docker run -it --gpus=all --rm nvcr.io/nvidia/k8s/cuda-sample:nbody nbody -benchmark` to test if the gpu virtualization is working everything works fine.

**Comment by dragonheat123** [comment] 2022-12-08 12:35
Hi, I had the same problem. 

Turns out that when installing tinycudann via pip install, it reads ENV TCNN_CUDA_ARCHITECTURES=86 off the Dockerfile, and compiled a version suitable to the compute capability of your GPU. [check out setup.py for tinycudann here](https://github.com/NVlabs/tiny-cuda-nn/blob/master/bindings/torch/setup.py)

You can try to replace 86 by the number you see when you run the code snippet:
`
import torch
major, minor = torch.cuda.get_device_capability()
compute_capabilities = [major * 10 + minor]
print(f"Obtained compute capability {compute_capabilities[0]} from PyTorch")
`

**Comment by ps1x** [comment] 2022-12-08 17:00
Does not work without setting TCNN_CUDA_ARCHITECTURES in Dockerfile
```
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-i5yqewf2/bindings/torch/setup.py", line 30, in <module>
          raise EnvironmentError("Unknown compute capability. Specify the target compute capabilities in the TCNN_CUDA_ARCHITECTURES environment variable or install PyTorch with the CUDA backend to detect it automatically.")
      OSError: Unknown compute capability. Specify the target compute capabilities in the TCNN_CUDA_ARCHITECTURES environment variable or install PyTorch with the CUDA backend to detect it automatically.
      No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
      Building PyTorch extension for tiny-cuda-nn version 1.6
      [end of output]
```

**Comment by b0ot** [comment] 2022-12-21 20:14
> Hi, I had the same problem.
> 
> Turns out that when installing tinycudann via pip install, it reads ENV TCNN_CUDA_ARCHITECTURES=86 off the Dockerfile, and compiles a version suitable to the compute capability of your GPU. [check out setup.py for tinycudann here](https://github.com/NVlabs/tiny-cuda-nn/blob/master/bindings/torch/setup.py)
> 
> You can try to replace 86 by the number you see when you run the code snippet:
> 
> ```
> import torch
> major, minor = torch.cuda.get_device_capability()
> compute_capabilities = [major * 10 + minor]
> print(f"Obtained compute capability {compute_capabilities[0]} from PyTorch")
> ```
> 
> or either omit setting ENV TCNN_CUDA_ARCHITECTURES in the Dockerfile, since setup.py will test for it anyway. (I didn't try this)

How do you modify a docker image?
Based on your code, mine should be '61'
```
ENV TCNN_CUDA_ARCHITECTURES=61
```
NVIDIA GeForce GTX 1070

**Comment by Scolymus** [comment] 2023-01-31 18:33
Same! works @dragonheat123 

In my case I was using the official docker to build another one and I needed compability 75. I forced reinstallation of torch and tinycudnn

```
FROM dromni/nerfstudio:0.1.15

ENV TCNN_CUDA_ARCHITECTURES=75
RUN python3.10 -m pip install --no-cache-dir --upgrade --force-reinstall --no-deps torch==1.12.1+cu116 torchvision==0.13.1+cu116 torchaudio==0.12.1 --extra-index-url https://download.pytorch.org/whl/cu116
RUN python3.10 -m pip install --no-cache-dir --upgrade --force-reinstall --no-deps git+https://github.com/NVlabs/tiny-cuda-nn.git#subdirectory=bindings/torch

# Do your stuff
```

**Comment by Zunhammer** [comment] 2023-02-01 13:06
Hi, could you please try again with ```docker pull dromni/nerfstudio:0.1.16```, The issue should be fixed, just waiting for confirmations that it is really solved as I cannot test on my own (only have RTX4000 available atm).
I'll update Dockerfile and descriptions as soon as I got the fix confirmed,
Thanks

**Comment by b0ot** [comment] 2023-02-01 14:28
I'm fairly new to Docker so it took me awhile to lookup how to run it again, especially on Windows after installing docker.

For other new people, all the following did in windows cmd
**Step 1**
`docker pull dromni/nerfstudio:0.1.16 `

You need the \\ since the path is windows.

That takes awhile to download, once complete:

**Step 2**
`docker run --gpus all -v C:\\Users\\your\\fullpath:\\createdFolder -v C:\\Users\\your\\fullpath\\.cache:/home/user/cache -p 7007:7007 --rm -it dromni/nerfstudio:0.1.16`

That now launches into a linux env

```
C:\Users\tom>docker run --gpus all -v C:\\Users\\tom\\docker_nerfstudio:\\docker_nerfstudio -v C:\\Users\\tom\\docker_nerfstudio\\.cache:/home/user/cache -p 7007:7007 --rm -it dromni/nerfstudio:0.1.16

==========
== CUDA ==
==========

CUDA Version 11.7.1

Container image Copyright (c) 2016-2022, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

[14:24:00] 🤷 .zshrc not found, skipping.                                                                 install.py:210
           🔍 Found .bashrc!                                                                              install.py:212
           ✔ Wrote new completion to /home/user/nerfstudio/scripts/completions/bash/_ns-install-cli!      install.py:117
           ✔ Wrote new completion to /home/user/nerfstudio/scripts/completions/bash/_ns-dev-test!         install.py:117
[14:24:01] ✔ Wrote new completion to /home/user/nerfstudio/scripts/completions/bash/_ns-process-data!     install.py:117
[14:24:03] ✔ Wrote new completion to /home/user/nerfstudio/scripts/completions/bash/_ns-download-data!    install.py:117
[14:24:05] ✔ Wrote new completion to /home/user/nerfstudio/scripts/completions/bash/_ns-render!           install.py:117
           ✔ Wrote new completion to /home/user/nerfstudio/scripts/completions/bash/_ns-eval!             install.py:117
[14:24:07] ✔ Wrote new completion to /home/user/nerfstudio/scripts/completions/bash/_ns-train!            install.py:117
           🙆 Completions installed to /home/user/.bashrc. Neat! Open a new shell to try them out.        install.py:184
All done!
user@8f9a64c9b11f:/workspace$
```

Since I can run this, I believe the issue this thread is discussing is now resolved
I can now run commands like ns-download-data and see info related to arguments / subcommands

However, I still seem to have some issues as if I try to run the **Training your first model** example, I have an error:
```
user@8f9a64c9b11f:/workspace$ ns-download-data nerfstudio --capture-name=poster
Traceback (most recent call last):
  File "/home/user/.local/bin/ns-download-data", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/user/nerfstudio/scripts/downloads/download_data.py", line 321, in entrypoint
    main(tyro.cli(Commands))
  File "/home/user/nerfstudio/scripts/downloads/download_data.py", line 313, in main
    dataset.save_dir.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: 'data'
```

However, this issue seems to be seperate from the topic in this thread and more similar to this [Issue 1309](https://github.com/nerfstudio-project/nerfstudio/issues/1309)

**Comment by Zunhammer** [comment] 2023-02-01 15:26
So the image is working fine, please use the option to set a user defined data folder for ns-download-data (should be --save-dir <dir>) (see https://docs.nerf.studio/en/latest/reference/cli/ns_download_data.html)
Also, in Windows you need to use \ as you already did, however on the docker side I think it should still be /. Try to use:
```
docker run --gpus all -v 'C:\Users\your\fullpath:/createdFolder' -v 'C:\Users\your\fullpath\.cache:/home/user/cache' -p 7007:7007 --rm -it dromni/nerfstudio:0.1.16
```
and then
```
ns-download-data nerfstudio --save-dir /createdFolder --capture-name=poster
```

**Closed** 2023-02-01 20:02 UTC

**Comment by eyildiz-ugoe** [comment] 2024-06-03 08:04
This problem exists without the docker installation as well.
