### ISSUE TITLE
[POTENTIAL BUG] Using ns-process-data gives worse result than convert to undistorted images to colmap

### ISSUE THREAD

**Issue by ichsan2895** [nerfstudio-project/nerfstudio#2849] opened 2024-01-30 13:27 UTC
**Describe the bug**
I have two different test how to create splatfacto dataset.

First, using `ns-process-data images`

Second, using `python3 convert.py` from INRIA Gaussian-splatting's github repo. It do not use any code from GS so it safe for using it as colmap license. It uses colmap source code for extracting undistorted images and SfM information from input images. 

Second result is always gives better result. In PSNR and SSIM. I know this way from @jb-ye and he pointed out maybe a bug in nerfstudio dataparser.

## **To Reproduce first dataset called `Vasedeck`**
**First way:**

Get `vasedeck` dataset from `nerf_real_360.zip` in this site (https://drive.google.com/drive/folders/128yBriW1IG_3NJ5Rp7APSTZsJqdJdfc1). Then copy paste the images to `IMAGES` folder.
```
ns-process-data images --data IMAGES --output-dir VASEDECK

ns-train splatfacto --logging.steps-per-log 200 --vis viewer+wandb --viewer.websocket-port 7007 \
    nerfstudio-data --load-3D-points True \
    --data VASEDECK --downscale-factor 1
```

**Second Way:**

create a folder called `VASEDECK`, and a subfolder called `input` which contains the images.

Go to INRIA GS's github repo, download it, and run `convert.py`.
```
python3 convert.py -s VASEDECK

ns-train splatfacto --data VASEDECK \
    --logging.steps-per-log 200 --vis viewer+wandb --viewer.websocket-port 7007 \
    colmap --colmap_path VASEDECK/sparse/0  --downscale-factor 1
```
**Expected behavior**
Second way becomes default way in `ns-process-data images` since it was better for splat quality. In this dataset, **I get extra 0,9 dB PSNR with second way in this dataset. It gains PSNR from 23,9 to 24,8 dB.**

**Screenshots**
![image](https://github.com/nerfstudio-project/nerfstudio/assets/60387342/6a500f01-4395-49ea-8650-7662c7bc1580)
![image](https://github.com/nerfstudio-project/nerfstudio/assets/60387342/187e7ab6-8169-4ed7-809f-ce01b1c6887e)

First way (left) and second way (right) as seen with `mkellogg` gaussian splat viewer

**Additional context**

- Uses `runpod` environment with `Ubuntu` 22.04.
- `Python 3.10.16`
- Nerfstudio v1.0.0
- `Colmap 3.8` with CUDA (built from source). I already use `Colmap 3.9.1` but **sometimes** get worse result since it can not create all undistorted images. So, I revert back to `colmap 3.8`
- `Torch 2.0.1+cu118`
- VGA RTX A6000 48GB
- RAM 62 GB

**Comment by jb-ye** [comment] 2024-01-30 16:00
As a side note, one potential root cause is the opencv bug tracked by https://github.com/opencv/opencv/issues/24831

One may have to re-validate this bug when incorporating the upstream fix from opencv.

**Comment by ichsan2895** [comment] 2024-01-30 21:56
If one of potential root cause is the opencv bug, Is it already fixed in this commit? https://github.com/nerfstudio-project/nerfstudio/pull/2726

**Comment by bobye** [comment] 2024-01-31 01:25
> If one of potential root cause is the opencv bug, Is it already fixed in this commit? #2726

No

**Comment by ichsan2895** [comment] 2024-02-10 16:27
I constantly get better result with **Second Way**. Now I try another dataset.

`Truck` dataset from sample Inria 3DGS which I processed by `colmap 3.8`
**Blue line =** First Way
PSNR = 25,97
**Red line =** Second Way
PSNR = 26,66

![image](https://github.com/nerfstudio-project/nerfstudio/assets/60387342/227f6441-120d-4241-a8b2-7d210cc2dece)

**Comment by ichsan2895** [comment] 2024-02-10 16:39
Purancak dataset from my friend drone which I processed by colmap 3.8
Blue line = First Way
PSNR = 21,68

Red line = Second Way
PSNR = 22,47

![image](https://github.com/nerfstudio-project/nerfstudio/assets/60387342/dcfb5431-1315-4dd9-9c7c-32554345db27)

**Comment by ichsan2895** [comment] 2024-02-10 16:47
`desolation` dataset from `ns-process-data`.
**Blue line =** First Way
PSNR = 21.62
**Red line =** Second Way
PSNR = 22.21

![image](https://github.com/nerfstudio-project/nerfstudio/assets/60387342/a1d417b3-0bdd-48fb-b23c-eea40e6def33)

**Comment by jb-ye** [comment] 2024-02-10 18:07
Thanks for confirming the issue @ichsan2895 i plan to take a look when I got time but if someone is willing to take a look earlier that would be great

**Comment by ichsan2895** [comment] 2024-02-10 18:18
> Thanks for confirming the issue @ichsan2895 i plan to take a look when I got time but if someone is willing to take a look earlier that would be great

Hello, thanks for your interest. If you or somebody have free time, take a look with my PR in https://github.com/nerfstudio-project/nerfstudio/pull/2896.

Yes the PR is not tidy. But I keep similar as original `python3 convert.py` to ensure the quality.

**Comment by ichsan2895** [comment] 2024-02-12 05:22
`desolation` dataset from `ns-download-data`.
**Blue line =** First Way
PSNR = 24.22

**Red line =** Second Way
PSNR = 24.97

![image](https://github.com/nerfstudio-project/nerfstudio/assets/60387342/a5f1baa8-587a-4dc6-96e4-46fe407b15b1)

**Comment by jb-ye** [comment] 2024-03-30 13:14
@ichsan2895 Could you try `ns-process-data images --method_method exhaustive --data IMAGES --output-dir VASEDECK`? I think the performance gap may be caused by the difference in colmap [options](https://github.com/nerfstudio-project/nerfstudio/blob/main/nerfstudio/process_data/colmap_converter_to_nerfstudio_dataset.py#L34).

**Comment by jb-ye** [comment] 2024-04-05 19:27
Another issue I realized is the opencv undistortion uses a different image coordinate convention than nerfstudio. I probably would try to fix it.

**Comment by jb-ye** [comment] 2024-04-12 19:55
A quick evaluation shows that the gap is not coming from splatfacto pipeline. Below I use the same colmap project processed as the second way in the main post (distorted version and undistorted version). 

```
# orange: train on undistorted images from colmap undistorter (resolution 3954x2975)
ns-train splatfacto --data vasedeck_fix/ --logging.local-writer.max-log-size=0 colmap --colmap_path=sparse/0 --downscale-factor 1  --images_path images

# blue: train on undistorted image from opencv undistortion (resolution 4031 x 3023).
ns-train splatfacto --data vasedeck_fix/ --logging.local-writer.max-log-size=0 colmap --colmap_path=distorted/sparse/0 --downscale-factor 1  --images_path input
```

Notice that PSNR evaluation on colmap undistorted images is slightly better than opencv undistorted image (PSNR 24.83 vs 24.57), this is expected, because the opencv undistorted image has higher resolution than colmap version.  

<img width="352" alt="Screenshot 2024-04-12 at 3 48 06 PM" src="https://github.com/nerfstudio-project/nerfstudio/assets/132313008/a3cab469-a254-4cd4-aa1e-872ba27a1bea">


The main gap between PSNR 24.57 vs 23.9 as reported may actually come from preprocessing steps. I highly suggest we use `exhaustive` in colmap preprocessing.

**Comment by jb-ye** [comment] 2024-08-26 19:34
fixed by #3382

**Closed by jb-ye** 2024-08-26 19:34 UTC
Labels: enhancement

**Comment by jb-ye** [comment] 2024-08-26 19:38
@ichsan2895 I think the root cause of this issue is found. See #3382

**Comment by ichsan2895** [comment] 2024-08-27 23:51
Thank you, Kudos to developers 😁 I will take a look later about this change
