### ISSUE TITLE
remote server can't connect renderer

### ISSUE THREAD

**Issue by jyC23333** [nerfstudio-project/nerfstudio#1781] opened 2023-04-20 07:39 UTC
I found the 0.2.1 version can't view the training process.
I'm using thi url : https://viewer.nerf.studio/versions/23-04-10-0/?websocket_url=ws://localhost:7007
![image](https://user-images.githubusercontent.com/110331827/233294340-aa98a7ed-9060-45f2-a177-bd7838416953.png)

But I can view this in 0.1.19, I'm wondering is it a bug?
0.1.19 url : https://viewer.nerf.studio/versions/23-03-9-0/?websocket_url=ws://localhost:7007

**Comment by brentyi** [comment] 2023-04-20 07:43
This may be a duplicate of #1735; getting #1779 merged will likely fix it.

**Comment by jyC23333** [comment] 2023-04-20 07:47
I'm using a remote server, I found that using vnc on server can view the training process.
But It fails to view in local by forwarding that port.

**Closed** 2023-04-20 07:51 UTC

**Comment by brentyi** [comment] 2023-04-20 07:53
Got it! The main difference between `0.1.19` and `0.2.1` is the change in the host address. I'd expect that to be the issue, #1779 will revert it.
