### ISSUE TITLE
"OSError: Could not find compatible tinycudann extension for compute capability 86"

### ISSUE THREAD

**Issue by rockywind** [nerfstudio-project/nerfstudio#1219] opened 2023-01-10 05:12 UTC
**Describe the bug**
When I run the script `ns-train nerfacto nuscenes-data --data-dir data/NuScenes --data scene-0061`. I met the error below.
````
(nerfstudio) zizhang.wu@shaxbw03:/SHFP12/02_bevdet/nerfstudio$ sh train.sh 
Traceback (most recent call last):
  File "/home/CN/zizhang.wu/anaconda3/envs/nerfstudio/bin/ns-train", line 5, in <module>
    from scripts.train import entrypoint
  File "/home/CN/zizhang.wu/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/scripts/train.py", line 50, in <module>
    from nerfstudio.configs.method_configs import AnnotatedBaseConfigUnion
  File "/home/CN/zizhang.wu/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/configs/method_configs.py", line 38, in <module>
    from nerfstudio.models.instant_ngp import InstantNGPModelConfig
  File "/home/CN/zizhang.wu/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/models/instant_ngp.py", line 38, in <module>
    from nerfstudio.field_components.field_heads import FieldHeadNames
  File "/home/CN/zizhang.wu/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/field_components/__init__.py", line 17, in <module>
    from .encodings import Encoding, ScalingAndOffset
  File "/home/CN/zizhang.wu/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/field_components/encodings.py", line 34, in <module>
    import tinycudann as tcnn
  File "/home/CN/zizhang.wu/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/tinycudann/__init__.py", line 9, in <module>
    from tinycudann.modules import free_temporary_memory, NetworkWithInputEncoding, Network, Encoding
  File "/home/CN/zizhang.wu/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/tinycudann/modules.py", line 35, in <module>
    raise EnvironmentError(f"Could not find compatible tinycudann extension for compute capability {system_compute_capability}.")
OSError: Could not find compatible tinycudann extension for compute capability 86.
````

**Comment by ChuangqHu** [comment] 2023-01-10 11:06
same problem, have you solved it？

**Comment by Alaa-Abboud** [comment] 2023-01-10 13:26
Same problem here; I would appreciate any guidance on the matter.

**Comment by tancik** [comment] 2023-01-27 18:46
Try running pip list | grep torch
The torch version should be 1.12.1+cu113 or 1.12.1+cu116
If the +cu... is missing, then you need to reinstall pytorch with cuda support, ie
pip install torch==1.12.1+cu113 torchvision==0.13.1+cu113 -f https://download.pytorch.org/whl/torch_stable.html

**Comment by YifuTao** [comment] 2023-02-16 00:44
I encountered a similar problem to this and #1283 #1189 as `tcnn` cannot find extension for compute capability `70`. The short answer is to make sure `tinycudann` for your specific GPU/CUDA compute capability is correctly built so that you can run `import tinycudann` in python.

For me, the problem is that I have two GPUs of compute compatability `70` and `86`. When I run 
```pip install git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch```
 it automatically chooses my first GPU (`86`) as the compute capability to build. I can run if specifying only one GPU e.g. `CUDA_VISIBLE_DEVICES=0 ns-train ...`, but not the other.

To use the other GPU (`70`), I need to specify it and re-build `tinycudann` from source for that particular compatability.
```
tiny-cuda-nn$ cd bindings/torch
tiny-cuda-nn/bindings/torch$ CUDA_VISIBLE_DEVICES=1 python setup.py install
```

**Comment by tancik** [comment] 2023-02-22 18:45
Closing, feel free to reopen if it is still and issue.

**Closed by tancik** 2023-02-22 18:45 UTC

**Comment by Zhentao-Liu** [comment] 2023-06-18 01:12
> I encountered a similar problem to this and #1283 #1189 as `tcnn` cannot find extension for compute capability `70`. The short answer is to make sure `tinycudann` for your specific GPU/CUDA compute capability is correctly built so that you can run `import tinycudann` in python.
> 
> For me, the problem is that I have two GPUs of compute compatability `70` and `86`. When I run `pip install git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch` it automatically chooses my first GPU (`86`) as the compute capability to build. I can run if specifying only one GPU e.g. `CUDA_VISIBLE_DEVICES=0 ns-train ...`, but not the other.
> 
> To use the other GPU (`70`), I need to specify it and re-build `tinycudann` from source for that particular compatability.
> 
> ```
> tiny-cuda-nn$ cd bindings/torch
> tiny-cuda-nn/bindings/torch$ CUDA_VISIBLE_DEVICES=1 python setup.py install
> ```

You mean if I choose another GPU, then it will work correctly?

**Comment by Zhentao-Liu** [comment] 2023-06-18 01:15
> I encountered a similar problem to this and #1283 #1189 as `tcnn` cannot find extension for compute capability `70`. The short answer is to make sure `tinycudann` for your specific GPU/CUDA compute capability is correctly built so that you can run `import tinycudann` in python.
> 
> For me, the problem is that I have two GPUs of compute compatability `70` and `86`. When I run `pip install git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch` it automatically chooses my first GPU (`86`) as the compute capability to build. I can run if specifying only one GPU e.g. `CUDA_VISIBLE_DEVICES=0 ns-train ...`, but not the other.
> 
> To use the other GPU (`70`), I need to specify it and re-build `tinycudann` from source for that particular compatability.
> 
> ```
> tiny-cuda-nn$ cd bindings/torch
> tiny-cuda-nn/bindings/torch$ CUDA_VISIBLE_DEVICES=1 python setup.py install
> ```

It did work for me after I change another GPU, thx a lot
