### ISSUE TITLE
Runtime Error on Installation

### ISSUE THREAD

**Issue by jeffreyianwilson** [nerfstudio-project/nerfstudio#713] opened 2022-10-06 15:45 UTC
**Describe the bug**
Runtime Error on Installation

Dependency Installation when running this commands
pip install torch==1.12.1+cu113 torchvision==0.13.1+cu113 -f https://download.pytorch.org/whl/torch_stable.html
pip install git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch

I have Visual Studio 2022 Installed.

  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\jeffr\AppData\Local\Temp\pip-req-build-mln5_7ks\bindings/torch\setup.py", line 52, in <module>
          raise RuntimeError("Could not locate a supported Microsoft Visual C++ installation")
      RuntimeError: Could not locate a supported Microsoft Visual C++ installation
      Building PyTorch extension for tiny-cuda-nn version 1.6
      Obtained compute capability 86 from PyTorch
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

**Comment by tancik** [comment] 2022-10-08 01:41
This looks like an issue with installing tiny-cuda-nn. 
You could try installing a local clone of the tcnn repo,
```
git clone https://github.com/NVlabs/tiny-cuda-nn.git
cd bindings/torch
python setup.py install
```

If that doesn't work, I'd recommend filing an issue in [their repo](https://github.com/NVlabs/tiny-cuda-nn/issues).

**Comment by tancik** [comment] 2022-11-11 19:53
Closing. Feel free to reopen if this is still an issue.

**Closed by tancik** 2022-11-11 19:53 UTC

**Comment by NagaPadma** [comment] 2023-12-11 13:16
> What worked for me was to install Visual Studio (NOT Visual Studio Code) and check the "Desktop development with C++" option.

thank you. i had the same problem but your soulution helped me. thanks again.

**Comment by skdzqy** [comment] 2023-12-31 21:39
> What worked for me was to install Visual Studio (NOT Visual Studio Code) and check the "Desktop development with C++" option.

I've already check the "Desktop development with c++", but i still received
python setup.py egg_info did not run successfully.
when install tcnn

and received
RuntimeError: Could not locate a supported Microsoft Visual C++ installation
when install tcnn by local clone

what should i do?

**Comment by PolarisXQ** [comment] 2024-07-22 07:15
> > What worked for me was to install Visual Studio (NOT Visual Studio Code) and check the "Desktop development with C++" option.
> 
> I've already check the "Desktop development with c++", but i still received python setup.py egg_info did not run successfully. when install tcnn
> 
> and received RuntimeError: Could not locate a supported Microsoft Visual C++ installation when install tcnn by local clone
> 
> what should i do?

I have the same situation as you. I guess the problem is drived from the error path of the building tool. What worked for me was to modify the path manually.

Clone the repo.

```bash
git clone https://github.com/NVlabs/tiny-cuda-nn.git --recursive
cd tiny-cuda-nn/bindings/torch
```

Modify the 'setup.py'. In function 'find_cl_path()' (about line 60),change the paths to where your Microsoft Visual C++ was installed.

for me,

```python
# original
# paths = sorted(glob.glob(f"C:\\{executable}\\Microsoft Visual Studio\\*\\{edition}\\VC\\Tools\\MSVC\\*\\bin\\Hostx64\\x64"), reverse=True)
# changed to
paths = sorted(glob.glob(f"D:\\VisualStudio\\VC\\Tools\\MSVC\\*\\bin\\Hostx64\\x64"), reverse=True)
```

then execute the command below to install tiny-cuda-nn

```
conda activate nerfstudio
python setup.py install
```
