### ISSUE TITLE
When I run NerfStudio on the Linux server, how can I open the webviewer locally?

### ISSUE THREAD

**Issue by ppjiong11** [nerfstudio-project/nerfstudio#1518] opened 2023-02-27 08:58 UTC
I entered WebViewer from VSCode's hyperlink, it shows the server disconnect

**Comment by tancik** [comment] 2023-02-27 17:30
So you are opening the viewer on the same machine that nerfstudio is training on? Can you post the outputs to the training command.

**Comment by ppjiong11** [comment] 2023-03-01 11:14
> So you are opening the viewer on the same machine that nerfstudio is training on? Can you post the outputs to the training command.

I run nerfstudio on the linux server by vscode, and i want to open the webviewer on local machine, how can i port forward the websocket port?

**Comment by tancik** [comment] 2023-03-03 02:40
In vscode you can open ports using the port window, ie
<img width="745" alt="image" src="https://user-images.githubusercontent.com/3310961/222617906-6d7839be-d26b-47ac-979d-1f06b555aafe.png">

**Comment by ppjiong11** [comment] 2023-03-15 13:05
> In vscode you can open ports using the port window, ie <img alt="image" width="745" src="https://user-images.githubusercontent.com/3310961/222617906-6d7839be-d26b-47ac-979d-1f06b555aafe.png">

Hello, I forwarded the port on VSCODE, but still showed the Connection Fail；I noticed that there is no bright green light in front of my port

**Comment by trltzy** [comment] 2023-08-17 12:28
I have the same problem, can I open the webviewer on another machine instead of locally?

**Comment by maturk** [comment] 2023-08-17 13:08
you can also try the command `ssh -L 7007:localhost:7007 username@your-server-IP` from the terminal window on your local machine. This forwards port 7007 from server to your local machine. Let me know if this works/helps you. If you get errors with this command, it is most likely caused by your server now allowing port forwarding (could be changed in server settings most likely).

**Comment by trltzy** [comment] 2023-08-17 13:22
thanks

**Comment by trltzy** [comment] 2023-08-17 13:45
I tried this command in cmd, with a password, but it was either denied permission or connection closed by port 22. But actually I can connect with my server using termius with the same username，server-IP and passwork.

**Comment by maturk** [comment] 2023-08-17 15:15
> I tried this command in cmd, with a password, but it was either denied permission or connection closed by port 22. But actually I can connect with my server using termius with the same username，server-IP and passwork.

I am not sure what termius is. Are you able to normally ssh to your server from cmd/powershell etc?

**Comment by trltzy** [comment] 2023-08-18 11:36
yes，I can access normall via ssh -p port-num root@server-ip, but I tried to tunnel between my client with the server, it always show the error "Permission denied(publickey)". I also tried to add my  public key into the server authorized_key file, but it seems not work. It's quite confusing...

**Comment by maturk** [comment] 2023-08-18 11:38
> yes，I can access normally via ssh -p port-num root@server-ip, but as I tried to tunnel between my client with the server, it always show the error "Permission denied(publickey)". I also tried to add my public key into the server authorized_key file, but it seems not work. It's quite confusing...

I see, sorry I am not too familiar with this, but it seems that your server is indeed blocking something for the port forwarding to work. Is this your own server or company server?

**Comment by trltzy** [comment] 2023-08-18 11:43
It's a cloud server I rent.

**Comment by maturk** [comment] 2023-08-18 11:44
> It's a cloud server I rent.

maybe you can ask the provider for details about port forwarding then. Sorry I cant help further...

**Comment by trltzy** [comment] 2023-08-18 11:45
Okay, thank you so much.

**Closed** 2023-08-18 14:02 UTC
