### ISSUE TITLE
"load-config" argument overrides other CLI arguments

### ISSUE THREAD

**Issue by iSach** [nerfstudio-project/nerfstudio#1729] opened 2023-04-13 09:54 UTC
**Describe the bug**
As would be expected, load-config should load the default values for all pipeline arguments, and afterwards other CLI arguments should be considered and loaded.

This is particularly useful when having some default config for a specific kind of experiment, and needing to tweak it from the CLI. 

With this problem, tweaks are impossible without modifying the YML file and other CLI arguments are just ignored.

**To Reproduce**
1. Train a model and have a config.yml
2. Try to train another model based on that config but with some tweaks, for example `ns-train --vis viewer model_trained_with_wandb/config.yml` 
3. `--vis viewer` is ignored.

**Expected behavior**
Supplementary arguments should not be ignored but rather should override the loaded config.

**Comment by tancik** [comment] 2023-04-14 00:10
Maybe @brentyi can chime in, I think he was looking into this. I believe it turns out to be more complicated than it would seem.

**Comment by brentyi** [comment] 2023-04-14 05:48
Yeah, it was more complicated than expected but the hardest parts of getting it working has been done, it just needs a last push and then testing. We have some discussion in #1281; I'm going to close this issue since it's the same but appreciate  you re-surfacing it @iSach.

Duplicate of #1281

**Comment by brentyi** [comment] 2023-04-14 05:48
Duplicate of #1281

**Closed by brentyi** 2023-04-14 05:48 UTC

**Comment by iSach** [comment] 2023-04-14 06:57
> Yeah, it was more complicated than expected but the hardest parts of getting it working has been done, it just needs a last push and then testing. We have some discussion in #1281; I'm going to close this issue since it's the same but appreciate you re-surfacing it @iSach.

My bad, thank you!
