### ISSUE TITLE
Download links (nerfstudio dataset) are down

### ISSUE THREAD

**Issue by dberga** [nerfstudio-project/nerfstudio#2564] opened 2023-10-27 06:33 UTC
Tried to re-download the nerfstudio-dataset and the links are down for some capture names (scenes). Say by running:

ns-download-data nerfstudio --capture-name all;

Resolving data.nerf.studio (data.nerf.studio)... 34.102.68.79                                                                                 
Connecting to data.nerf.studio (data.nerf.studio)|34.102.68.79|:443... connected.                                                             
HTTP request sent, awaiting response... 404 File not found                                                                                    
2023-10-27 08:21:23 ERROR 404: File not found.

The links redirect to this:
https://data.nerf.studio/nerfstudio/{CAPTURE_NAME}.zip

But only these are the capture names that cannot be found: Egypt,person,kitchen,plane,dozer,floating-tree,aspen,stump,sculpture,Giannini-Hall

The rest of capture names downloaded successfully.

**Comment by tancik** [comment] 2023-10-27 16:41
Duplicate of #2544

**Closed by tancik** 2023-10-27 16:41 UTC
